name: build-books-index

on:
  push:
    paths:
      - "books/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate books.json + kindle.html
        run: node generate.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add books.json kindle.html

          git commit -m "auto update books index + kindle page" || echo "no changes"

      - name: Push changes
        run: git push
